const data = [
  {
    reletedId: 7,
    nameAm: "Плата Am",
    nameRu: "Плата Ru",
    nameEn: "Плата EN",
    nameGe: "Плата Ge",
    descAm: "Плата DESC Am",
    descRu: "Плата DESC Ru",
    destEn: "Плата DESC EN",
    descGe: "Плата DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "Монетник Am",
    nameRu: "Монетник Ru",
    nameEn: "Монетник EN",
    nameGe: "Монетник Ge",
    descAm: "Монетник DESC Am",
    descRu: "Монетник DESC Ru",
    destEn: "Монетник DESC EN",
    descGe: "Монетник DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "Система Am",
    nameRu: "Система Ru",
    nameEn: "Система EN",
    nameGe: "Система Ge",
   descAm: "Система DESC Am",
    descRu: "Система DESC Ru",
    destEn: "Система DESC EN",
    descGe: "Система DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "режима(функция) Am",
    nameRu: "режима(функция) Ru",
    nameEn: "режима(функция) EN",
    nameGe: "режима(функция) Ge",
    descAm: "режима(функция) DESC Am",
    descRu: "режима(функция) DESC Ru",
    destEn: "режима(функция) DESC EN",
    descGe: "режима(функция) DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    descAm: "Картоприемник DESC Am",
    descRu: "Картоприемник DESC Ru",
    destEn: "Картоприемник DESC EN",
    descGe: "Картоприемник DESC Ge",
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    descAm: "Обогреватель для модуля DESC Am",
    descRu: "Обогреватель для модуля DESC Ru",
    destEn: "Обогреватель для модуля DESC EN",
    descGe: "Обогреватель для модуля DESC Ge",
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },

  {
    reletedId: 8,
    nameAm: "Плата Am",
    nameRu: "Плата Ru",
    nameEn: "Плата EN",
    nameGe: "Плата Ge",
    descAm: "Плата DESC Am",
    descRu: "Плата DESC Ru",
    destEn: "Плата DESC EN",
    descGe: "Плата DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "Монетник Am",
    nameRu: "Монетник Ru",
    nameEn: "Монетник EN",
    nameGe: "Монетник Ge",
    descAm: "Монетник DESC Am",
    descRu: "Монетник DESC Ru",
    destEn: "Монетник DESC EN",
    descGe: "Монетник DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "Система Am",
    nameRu: "Система Ru",
    nameEn: "Система EN",
    nameGe: "Система Ge",
    descAm: "Система DESC Am",
    descRu: "Система DESC Ru",
    destEn: "Система DESC EN",
    descGe: "Система DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "режима(функция) Am",
    nameRu: "режима(функция) Ru",
    nameEn: "режима(функция) EN",
    nameGe: "режима(функция) Ge",
    descAm: "режима(функция) DESC Am",
    descRu: "режима(функция) DESC Ru",
    destEn: "режима(функция) DESC EN",
    descGe: "режима(функция) DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    descAm: "Картоприемник DESC Am",
    descRu: "Картоприемник DESC Ru",
    destEn: "Картоприемник DESC EN",
    descGe: "Картоприемник DESC Ge",
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
   descAm: "Обогреватель для модуля DESC Am",
    descRu: "Обогреватель для модуля DESC Ru",
    destEn: "Обогреватель для модуля DESC EN",
    descGe: "Обогреватель для модуля DESC Ge",
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },

  {
    reletedId: 9,
    nameAm: "Плата Am",
    nameRu: "Плата Ru",
    nameEn: "Плата EN",
    nameGe: "Плата Ge",
    descAm: "Плата DESC Am",
    descRu: "Плата DESC Ru",
    destEn: "Плата DESC EN",
    descGe: "Плата DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "Монетник Am",
    nameRu: "Монетник Ru",
    nameEn: "Монетник EN",
    nameGe: "Монетник Ge",
    descAm: "Монетник DESC Am",
    descRu: "Монетник DESC Ru",
    destEn: "Монетник DESC EN",
    descGe: "Монетник DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "Система Am",
    nameRu: "Система Ru",
    nameEn: "Система EN",
    nameGe: "Система Ge",
    descAm: "Система DESC Am",
    descRu: "Система DESC Ru",
    destEn: "Система DESC EN",
    descGe: "Система DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "режима(функция) Am",
    nameRu: "режима(функция) Ru",
    nameEn: "режима(функция) EN",
    nameGe: "режима(функция) Ge",
    descAm: "режима(функция) DESC Am",
    descRu: "режима(функция) DESC Ru",
    destEn: "режима(функция) DESC EN",
    descGe: "режима(функция) DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    descAm: "Картоприемник DESC Am",
    descRu: "Картоприемник DESC Ru",
    destEn: "Картоприемник DESC EN",
    descGe: "Картоприемник DESC Ge",
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    descAm: "Обогреватель для модуля DESC Am",
    descRu: "Обогреватель для модуля DESC Ru",
    destEn: "Обогреватель для модуля DESC EN",
    descGe: "Обогреватель для модуля DESC Ge",
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
];

module.exports = data;
