const data = [
  {
    reletedId: 1,
    nameAm: "Motor Am",
    nameRu: "Motor Ru",
    nameEn: "Motor EN",
    nameGe: "Motor Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 1,
    nameAm: "Доп. Am",
    nameRu: "Доп. Ru",
    nameEn: "Доп. EN",
    nameGe: "Доп. Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 2,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 1,
    nameAm: "Выберите модуль! Am",
    nameRu: "Выберите модуль! Ru",
    nameEn: "Выберите модуль! EN",
    nameGe: "Выберите модуль! Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 3,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
];

module.exports = data;
