const data = [
  {
    itemId: 1,
    nameAm: "Плата - PRO 5XL (стандартная) Am",
    nameRu: "Плата - PRO 5XL (стандартная) Ru",
    nameEn: "Плата - PRO 5XL (стандартная) EN",
    nameGe: "Плата - PRO 5XL (стандартная) Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Плата - PRO 5XL (стандартная) DESC Am",
    descRu: "Плата - PRO 5XL (стандартная) DESC Ru",
    destEn: "Плата - PRO 5XL (стандартная) DESC EN",
    descGe: "Плата - PRO 5XL (стандартная) DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 2,
    nameAm: "Монетник(китайский) BL616 Am",
    nameRu: "Монетник(китайский) BL616 Ru",
    nameEn: "Монетник(китайский) BL616 EN",
    nameGe: "Монетник(китайский) BL616 Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Монетник(китайский) BL616 DESC Am",
    descRu: "Монетник(китайский) BL616 DESC Ru",
    destEn: "Монетник(китайский) BL616 DESC EN",
    descGe: "Монетник(китайский) BL616 DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 2,
    nameAm: "Монетник(итальянский) Comestero RM5 Am",
    nameRu: "Монетник(итальянский) Comestero RM5 Ru",
    nameEn: "Монетник(итальянский) Comestero RM5 EN",
    nameGe: "Монетник(итальянский) Comestero RM5 Ge",
    price: "120",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Монетник(итальянский) Comestero RM5 DESC Am",
    descRu: "Монетник(итальянский) Comestero RM5 DESC Ru",
    destEn: "Монетник(итальянский) Comestero RM5 DESC EN",
    descGe: "Монетник(итальянский) Comestero RM5 DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 3,
    nameAm: "Система стандартная Am",
    nameRu: "Система стандартная Ru",
    nameEn: "Система стандартная EN",
    nameGe: "Система стандартная Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Система стандартная DESC Am",
    descRu: "Система стандартная DESC Ru",
    destEn: "Система стандартная DESC EN",
    descGe: "Система стандартная DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 3,
    nameAm: "Система инверторнаяInverter System image Am",
    nameRu: "Система инверторнаяInverter System image Ru",
    nameEn: "Система инверторнаяInverter System image EN",
    nameGe: "Система инверторнаяInverter System image Ge",
    price: "520",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Система инверторнаяInverter System image DESC Am",
    descRu: "Система инверторнаяInverter System image DESC Ru",
    destEn: "Система инверторнаяInverter System image DESC EN",
    descGe: "Система инверторнаяInverter System image DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 4,
    nameAm: "3 режима(функция) Am",
    nameRu: "3 режима(функция) Ru",
    nameEn: "3 режима(функция) EN",
    nameGe: "3 режима(функция) Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "3-й режим DESC Am",
    descRu: "3-й режим DESC Ru",
    destEn: "3-й режим DESC EN",
    descGe: "3-й режим DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 4,
    nameAm: "4 режима(функция) Am",
    nameRu: "4 режима(функция) Ru",
    nameEn: "4 режима(функция) EN",
    nameGe: "4 режима(функция) Ge",
    price: "10",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "4-й режим DESC Am",
    descRu: "4-й режим DESC Ru",
    destEn: "4-й режим DESC EN",
    descGe: "4-й режим DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 4,
    nameAm: "5 режима(функция) Am",
    nameRu: "5 режима(функция) Ru",
    nameEn: "5 режима(функция) EN",
    nameGe: "5 режима(функция) Ge",
    price: "30",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "5-й режим DESC Am",
    descRu: "5-й режим DESC Ru",
    destEn: "5-й режим DESC EN",
    descGe: "5-й режим DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 5,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    price: "115",
    descAm: "Картоприемник DESC Am",
    descRu: "Картоприемник DESC Ru",
    destEn: "Картоприемник DESC EN",
    descGe: "Картоприемник DESC Ge",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 6,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    price: "30",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Обогреватель для модуля DESC Am",
    descRu: "Обогреватель для модуля DESC Ru",
    destEn: "Обогреватель для модуля DESC EN",
    descGe: "Обогреватель для модуля DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },

  {
    itemId: 7,
    nameAm: "Плата - PRO 5XL (стандартная) Am",
    nameRu: "Плата - PRO 5XL (стандартная) Ru",
    nameEn: "Плата - PRO 5XL (стандартная) EN",
    nameGe: "Плата - PRO 5XL (стандартная) Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Плата - PRO 5XL (стандартная) DESC Am",
    descRu: "Плата - PRO 5XL (стандартная) DESC Ru",
    destEn: "Плата - PRO 5XL (стандартная) DESC EN",
    descGe: "Плата - PRO 5XL (стандартная) DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 8,
    nameAm: "Монетник(китайский) BL616 Am",
    nameRu: "Монетник(китайский) BL616 Ru",
    nameEn: "Монетник(китайский) BL616 EN",
    nameGe: "Монетник(китайский) BL616 Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Монетник(китайский) BL616 DESC Am",
    descRu: "Монетник(китайский) BL616 DESC Ru",
    destEn: "Монетник(китайский) BL616 DESC EN",
    descGe: "Монетник(китайский) BL616 DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 8,
    nameAm: "Монетник(итальянский) Comestero RM5 Am",
    nameRu: "Монетник(итальянский) Comestero RM5 Ru",
    nameEn: "Монетник(итальянский) Comestero RM5 EN",
    nameGe: "Монетник(итальянский) Comestero RM5 Ge",
    price: "120",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Монетник(итальянский) Comestero RM5 DESC Am",
    descRu: "Монетник(итальянский) Comestero RM5 DESC Ru",
    destEn: "Монетник(итальянский) Comestero RM5 DESC EN",
    descGe: "Монетник(итальянский) Comestero RM5 DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 9,
    nameAm: "Система стандартная Am",
    nameRu: "Система стандартная Ru",
    nameEn: "Система стандартная EN",
    nameGe: "Система стандартная Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Система стандартная DESC Am",
    descRu: "Система стандартная DESC Ru",
    destEn: "Система стандартная DESC EN",
    descGe: "Система стандартная DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 9,
    nameAm: "Система инверторнаяInverter System image Am",
    nameRu: "Система инверторнаяInverter System image Ru",
    nameEn: "Система инверторнаяInverter System image EN",
    nameGe: "Система инверторнаяInverter System image Ge",
    price: "520",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Система инверторнаяInverter System image DESC Am",
    descRu: "Система инверторнаяInverter System image DESC Ru",
    destEn: "Система инверторнаяInverter System image DESC EN",
    descGe: "Система инверторнаяInverter System image DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 10,
    nameAm: "3 режима(функция) Am",
    nameRu: "3 режима(функция) Ru",
    nameEn: "3 режима(функция) EN",
    nameGe: "3 режима(функция) Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "3-й режим DESC Am",
    descRu: "3-й режим DESC Ru",
    destEn: "3-й режим DESC EN",
    descGe: "3-й режим DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 10,
    nameAm: "4 режима(функция) Am",
    nameRu: "4 режима(функция) Ru",
    nameEn: "4 режима(функция) EN",
    nameGe: "4 режима(функция) Ge",
    price: "10",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "4-й режим DESC Am",
    descRu: "4-й режим DESC Ru",
    destEn: "4-й режим DESC EN",
    descGe: "4-й режим DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 10,
    nameAm: "5 режима(функция) Am",
    nameRu: "5 режима(функция) Ru",
    nameEn: "5 режима(функция) EN",
    nameGe: "5 режима(функция) Ge",
    price: "30",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "5-й режим DESC Am",
    descRu: "5-й режим DESC Ru",
    destEn: "5-й режим DESC EN",
    descGe: "5-й режим DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 11,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    price: "115",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Картоприемник DESC Am",
    descRu: "Картоприемник DESC Ru",
    destEn: "Картоприемник DESC EN",
    descGe: "Картоприемник DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 12,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    price: "30",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Обогреватель для модуля DESC Am",
    descRu: "Обогреватель для модуля DESC Ru",
    destEn: "Обогреватель для модуля DESC EN",
    descGe: "Обогреватель для модуля DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },

  {
    itemId: 13,
    nameAm: "Плата - PRO 5XL (стандартная) Am",
    nameRu: "Плата - PRO 5XL (стандартная) Ru",
    nameEn: "Плата - PRO 5XL (стандартная) EN",
    nameGe: "Плата - PRO 5XL (стандартная) Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Плата - PRO 5XL (стандартная) DESC Am",
    descRu: "Плата - PRO 5XL (стандартная) DESC Ru",
    destEn: "Плата - PRO 5XL (стандартная) DESC EN",
    descGe: "Плата - PRO 5XL (стандартная) DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 14,
    nameAm: "Монетник(китайский) BL616 Am",
    nameRu: "Монетник(китайский) BL616 Ru",
    nameEn: "Монетник(китайский) BL616 EN",
    nameGe: "Монетник(китайский) BL616 Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Монетник(китайский) BL616 DESC Am",
    descRu: "Монетник(китайский) BL616 DESC Ru",
    destEn: "Монетник(китайский) BL616 DESC EN",
    descGe: "Монетник(китайский) BL616 DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 14,
    nameAm: "Монетник(итальянский) Comestero RM5 Am",
    nameRu: "Монетник(итальянский) Comestero RM5 Ru",
    nameEn: "Монетник(итальянский) Comestero RM5 EN",
    nameGe: "Монетник(итальянский) Comestero RM5 Ge",
    price: "120",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Монетник(итальянский) Comestero RM5 DESC Am",
    descRu: "Монетник(итальянский) Comestero RM5 DESC Ru",
    destEn: "Монетник(итальянский) Comestero RM5 DESC EN",
    descGe: "Монетник(итальянский) Comestero RM5 DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 15,
    nameAm: "Система стандартная Am",
    nameRu: "Система стандартная Ru",
    nameEn: "Система стандартная EN",
    nameGe: "Система стандартная Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Система стандартная DESC Am",
    descRu: "Система стандартная DESC Ru",
    destEn: "Система стандартная DESC EN",
    descGe: "Система стандартная DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 15,
    nameAm: "Система инверторнаяInverter System image Am",
    nameRu: "Система инверторнаяInverter System image Ru",
    nameEn: "Система инверторнаяInverter System image EN",
    nameGe: "Система инверторнаяInverter System image Ge",
    price: "520",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Система инверторнаяInverter System image DESC Am",
    descRu: "Система инверторнаяInverter System image DESC Ru",
    destEn: "Система инверторнаяInverter System image DESC EN",
    descGe: "Система инверторнаяInverter System image DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 16,
    nameAm: "3 режима(функция) Am",
    nameRu: "3 режима(функция) Ru",
    nameEn: "3 режима(функция) EN",
    nameGe: "3 режима(функция) Ge",
    price: "0",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "3-й режим DESC Am",
    descRu: "3-й режим DESC Ru",
    destEn: "3-й режим DESC EN",
    descGe: "3-й режим DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 16,
    nameAm: "4 режима(функция) Am",
    nameRu: "4 режима(функция) Ru",
    nameEn: "4 режима(функция) EN",
    nameGe: "4 режима(функция) Ge",
    price: "10",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "4-й режим DESC Am",
    descRu: "4-й режим DESC Ru",
    destEn: "4-й режим DESC EN",
    descGe: "4-й режим DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 16,
    nameAm: "5 режима(функция) Am",
    nameRu: "5 режима(функция) Ru",
    nameEn: "5 режима(функция) EN",
    nameGe: "5 режима(функция) Ge",
    price: "30",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "5-й режим DESC Am",
    descRu: "5-й режим DESC Ru",
    destEn: "5-й режим DESC EN",
    descGe: "5-й режим DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 17,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    price: "115",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Картоприемник DESC Am",
    descRu: "Картоприемник DESC Ru",
    destEn: "Картоприемник DESC EN",
    descGe: "Картоприемник DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 18,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    price: "30",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc9APxkj0xClmrU3PpMZglHQkx446nQPG6lA&s",

    descAm: "Обогреватель для модуля DESC Am",
    descRu: "Обогреватель для модуля DESC Ru",
    destEn: "Обогреватель для модуля DESC EN",
    descGe: "Обогреватель для модуля DESC Ge",
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
];

module.exports = data;
