const data = [
  {
    itemId: 1,
    nameAm: "Motor 5.5kw (Nikoloni) and Pump 200bar 15L Am",
    nameRu: "Motor 5.5kw (Nikoloni) and Pump 200bar 15L Ru",
    nameEn: "Motor 5.5kw (Nikoloni) and Pump 200bar 15L EN",
    nameGe: "Motor 5.5kw (Nikoloni) and Pump 200bar 15L Ge",
    price: "250",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    showIn: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 1,
    nameAm: "Motor 6.3kw (Nikoloni) and Pump 200bar 18L Am",
    nameRu: "Motor 6.3kw (Nikoloni) and Pump 200bar 18L Ru",
    nameEn: "Motor 6.3kw (Nikoloni) and Pump 200bar 18L EN",
    nameGe: "Motor 6.3kw (Nikoloni) and Pump 200bar 18L Ge",
    showIn: false,
    price: "250",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 2,
    nameAm: "Гидроударник Am",
    nameRu: "Гидроударник Ru",
    nameEn: "Гидроударник EN",
    nameGe: "Гидроударник Ge",
    showIn: false,
    price: "250",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 2,
    nameAm: "Зимний режим Am",
    nameRu: "Зимний режим Ru",
    nameEn: "Зимний режим EN",
    nameGe: "Зимний режим Ge",
    showIn: false,
    price: "250",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 2,
    nameAm: "Стоп режим Am",
    nameRu: "Стоп режим Ru",
    nameEn: "Стоп режим EN",
    nameGe: "Стоп режим Ge",
    showIn: false,
    price: "250",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 2,
    nameAm: "4-й режим Am",
    nameRu: "4-й режим Ru",
    nameEn: "4-й режим EN",
    nameGe: "4-й режим Ge",
    showIn: false,
    price: "250",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 3,
    nameAm: " Mодуль A Am",
    nameRu: " Mодуль A Ru",
    nameEn: " Mодуль A EN",
    nameGe: " Mодуль A Ge",
    showIn: true,
    price: "250",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    image:
      "https://cdn.prod.website-files.com/62d84e447b4f9e7263d31e94/6557420216a456cfaef685c0_6399a4d27711a5ad2c9bf5cd_ben-sweet-2LowviVHZ-E-unsplash-1-p-1600.jpg",

    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 3,
    nameAm: " Mодуль b Am",
    nameRu: " Mодуль b Ru",
    nameEn: " Mодуль b EN",
    nameGe: " Mодуль b Ge",
    showIn: true,
    price: "250",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8O-_YcxaWU3mDT89zm8BfkRuGmJOqnQUw8WOzlfb8ti_36jwFIlIqKRj-2K3piIiOuzY&usqp=CAU",

    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 3,
    nameAm: " Mодуль C Am",
    nameRu: " Mодуль C Ru",
    nameEn: " Mодуль C EN",
    nameGe: " Mодуль C Ge",
    showIn: true,
    price: "250",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    image:
      "https://media.istockphoto.com/id/504128865/fr/photo/femme-violoniste.jpg?s=612x612&w=0&k=20&c=alUOsUN77On4XyZncb8Yk47aUUrzSBoWgnimAPbkEv4=",

    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
];

module.exports = data;
