const data = [
  {
    reletedId: 1,
    nameAm: "Motor Am",
    nameRu: "Motor Ru",
    nameEn: "Motor EN",
    nameGe: "Motor Ge",
    descAm: "Motor DESC Am",
    descRu: "Motor DESC Ru",
    destEn: "Motor DESC EN",
    descGe: "Motor DESC Ge",
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 1,
    nameAm: "Доп. Am",
    nameRu: "Доп. Ru",
    nameEn: "Доп. EN",
    nameGe: "Доп. Ge",
    descAm: "Доп. DESC Am",
    descRu: "Доп. DESC Ru",
    destEn: "Доп. DESC EN",
    descGe: "Доп. DESC Ge",
    order: 2,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 1,
    nameAm: "Выберите модуль! Am",
    nameRu: "Выберите модуль! Ru",
    nameEn: "Выберите модуль! EN",
    nameGe: "Выберите модуль! Ge",
    descAm: "Выберите модуль!DESC Am",
    descRu: "Выберите модуль!DESC Ru",
    destEn: "Выберите модуль!DESC EN",
    descGe: "Выберите модуль!DESC Ge",
    order: 3,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 1,
    nameAm: "Mодуль Am",
    nameRu: "Mодуль Ru",
    nameEn: "Mодуль EN",
    nameGe: "Mодуль Ge",
    descAm: "Mодуль DESC Am",
    descRu: "Mодуль DESC Ru",
    destEn: "Mодуль DESC EN",
    descGe: "Mодуль DESC Ge",
    order: 4,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
];

module.exports = data;
