const data = [
  {
    itemId: 1,
    nameAm: "Плата - PRO 5XL (стандартная) Am",
    nameRu: "Плата - PRO 5XL (стандартная) Ru",
    nameEn: "Плата - PRO 5XL (стандартная) EN",
    nameGe: "Плата - PRO 5XL (стандартная) Ge",
    price: "0",
    showIn: false,
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 2,
    nameAm: "Монетник(китайский) BL616 Am",
    nameRu: "Монетник(китайский) BL616 Ru",
    nameEn: "Монетник(китайский) BL616 EN",
    nameGe: "Монетник(китайский) BL616 Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 2,
    nameAm: "Монетник(итальянский) Comestero RM5 Am",
    nameRu: "Монетник(итальянский) Comestero RM5 Ru",
    nameEn: "Монетник(итальянский) Comestero RM5 EN",
    nameGe: "Монетник(итальянский) Comestero RM5 Ge",
    showIn: false,
    price: "120",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 3,
    nameAm: "Система стандартная Am",
    nameRu: "Система стандартная Ru",
    nameEn: "Система стандартная EN",
    nameGe: "Система стандартная Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 3,
    nameAm: "Система инверторнаяInverter System image Am",
    nameRu: "Система инверторнаяInverter System image Ru",
    nameEn: "Система инверторнаяInverter System image EN",
    nameGe: "Система инверторнаяInverter System image Ge",
    showIn: false,
    price: "520",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 4,
    nameAm: "3 режима(функция) Am",
    nameRu: "3 режима(функция) Ru",
    nameEn: "3 режима(функция) EN",
    nameGe: "3 режима(функция) Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 4,
    nameAm: "4 режима(функция) Am",
    nameRu: "4 режима(функция) Ru",
    nameEn: "4 режима(функция) EN",
    nameGe: "4 режима(функция) Ge",
    showIn: false,
    price: "10",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 4,
    nameAm: "5 режима(функция) Am",
    nameRu: "5 режима(функция) Ru",
    nameEn: "5 режима(функция) EN",
    nameGe: "5 режима(функция) Ge",
    showIn: false,
    price: "30",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 5,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    showIn: false,
    price: "115",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 6,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    showIn: false,
    price: "30",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },

  {
    itemId: 7,
    nameAm: "Плата - PRO 5XL (стандартная) Am",
    nameRu: "Плата - PRO 5XL (стандартная) Ru",
    nameEn: "Плата - PRO 5XL (стандартная) EN",
    nameGe: "Плата - PRO 5XL (стандартная) Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 8,
    nameAm: "Монетник(китайский) BL616 Am",
    nameRu: "Монетник(китайский) BL616 Ru",
    nameEn: "Монетник(китайский) BL616 EN",
    nameGe: "Монетник(китайский) BL616 Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 8,
    nameAm: "Монетник(итальянский) Comestero RM5 Am",
    nameRu: "Монетник(итальянский) Comestero RM5 Ru",
    nameEn: "Монетник(итальянский) Comestero RM5 EN",
    nameGe: "Монетник(итальянский) Comestero RM5 Ge",
    showIn: false,
    price: "120",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 9,
    nameAm: "Система стандартная Am",
    nameRu: "Система стандартная Ru",
    nameEn: "Система стандартная EN",
    nameGe: "Система стандартная Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 9,
    nameAm: "Система инверторнаяInverter System image Am",
    nameRu: "Система инверторнаяInverter System image Ru",
    nameEn: "Система инверторнаяInverter System image EN",
    nameGe: "Система инверторнаяInverter System image Ge",
    showIn: false,
    price: "520",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 10,
    nameAm: "3 режима(функция) Am",
    nameRu: "3 режима(функция) Ru",
    nameEn: "3 режима(функция) EN",
    nameGe: "3 режима(функция) Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 10,
    nameAm: "4 режима(функция) Am",
    nameRu: "4 режима(функция) Ru",
    nameEn: "4 режима(функция) EN",
    nameGe: "4 режима(функция) Ge",
    showIn: false,
    price: "10",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 10,
    nameAm: "5 режима(функция) Am",
    nameRu: "5 режима(функция) Ru",
    nameEn: "5 режима(функция) EN",
    nameGe: "5 режима(функция) Ge",
    showIn: false,
    price: "30",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 11,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    showIn: false,
    price: "115",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 12,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    showIn: false,
    price: "30",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },

  {
    itemId: 13,
    nameAm: "Плата - PRO 5XL (стандартная) Am",
    nameRu: "Плата - PRO 5XL (стандартная) Ru",
    nameEn: "Плата - PRO 5XL (стандартная) EN",
    nameGe: "Плата - PRO 5XL (стандартная) Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 14,
    nameAm: "Монетник(китайский) BL616 Am",
    nameRu: "Монетник(китайский) BL616 Ru",
    nameEn: "Монетник(китайский) BL616 EN",
    nameGe: "Монетник(китайский) BL616 Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 14,
    nameAm: "Монетник(итальянский) Comestero RM5 Am",
    nameRu: "Монетник(итальянский) Comestero RM5 Ru",
    nameEn: "Монетник(итальянский) Comestero RM5 EN",
    nameGe: "Монетник(итальянский) Comestero RM5 Ge",
    showIn: false,
    price: "120",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 15,
    nameAm: "Система стандартная Am",
    nameRu: "Система стандартная Ru",
    nameEn: "Система стандартная EN",
    nameGe: "Система стандартная Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 15,
    nameAm: "Система инверторнаяInverter System image Am",
    nameRu: "Система инверторнаяInverter System image Ru",
    nameEn: "Система инверторнаяInverter System image EN",
    nameGe: "Система инверторнаяInverter System image Ge",
    showIn: false,
    price: "520",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 16,
    nameAm: "3 режима(функция) Am",
    nameRu: "3 режима(функция) Ru",
    nameEn: "3 режима(функция) EN",
    nameGe: "3 режима(функция) Ge",
    showIn: false,
    price: "0",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 16,
    nameAm: "4 режима(функция) Am",
    nameRu: "4 режима(функция) Ru",
    nameEn: "4 режима(функция) EN",
    nameGe: "4 режима(функция) Ge",
    showIn: false,
    price: "10",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 16,
    nameAm: "5 режима(функция) Am",
    nameRu: "5 режима(функция) Ru",
    nameEn: "5 режима(функция) EN",
    nameGe: "5 режима(функция) Ge",
    showIn: false,
    price: "30",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 17,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    showIn: false,
    price: "115",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    itemId: 18,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    showIn: false,
    price: "30",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
];

module.exports = data;
