const data = [
  {
    reletedId: 7,
    nameAm: "Плата Am",
    nameRu: "Плата Ru",
    nameEn: "Плата EN",
    nameGe: "Плата Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "Монетник Am",
    nameRu: "Монетник Ru",
    nameEn: "Монетник EN",
    nameGe: "Монетник Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "Система Am",
    nameRu: "Система Ru",
    nameEn: "Система EN",
    nameGe: "Система Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "режима(функция) Am",
    nameRu: "режима(функция) Ru",
    nameEn: "режима(функция) EN",
    nameGe: "режима(функция) Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 7,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },

  {
    reletedId: 8,
    nameAm: "Плата Am",
    nameRu: "Плата Ru",
    nameEn: "Плата EN",
    nameGe: "Плата Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "Монетник Am",
    nameRu: "Монетник Ru",
    nameEn: "Монетник EN",
    nameGe: "Монетник Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "Система Am",
    nameRu: "Система Ru",
    nameEn: "Система EN",
    nameGe: "Система Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "режима(функция) Am",
    nameRu: "режима(функция) Ru",
    nameEn: "режима(функция) EN",
    nameGe: "режима(функция) Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 8,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },

  {
    reletedId: 9,
    nameAm: "Плата Am",
    nameRu: "Плата Ru",
    nameEn: "Плата EN",
    nameGe: "Плата Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "Монетник Am",
    nameRu: "Монетник Ru",
    nameEn: "Монетник EN",
    nameGe: "Монетник Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "Система Am",
    nameRu: "Система Ru",
    nameEn: "Система EN",
    nameGe: "Система Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "режима(функция) Am",
    nameRu: "режима(функция) Ru",
    nameEn: "режима(функция) EN",
    nameGe: "режима(функция) Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: true,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "Картоприемник Am",
    nameRu: "Картоприемник Ru",
    nameEn: "Картоприемник EN",
    nameGe: "Картоприемник Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    reletedId: 9,
    nameAm: "Обогреватель для модуля Am",
    nameRu: "Обогреватель для модуля Ru",
    nameEn: "Обогреватель для модуля EN",
    nameGe: "Обогреватель для модуля Ge",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    order: 1,
    require: false,
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
];

module.exports = data;
