const data = [
  {
    titleAm: "Чернение шин  AM",
    titleRu: "Чернение шин Ru",
    titleEn: "Чернение шин En",
    titleGe: "Чернение шин GE",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    titleAm: "JSX Разменник  AM",
    titleRu: "JSX Разменник Ru",
    titleEn: "JSX Разменник En",
    titleGe: "JSX Разменник GE",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
  {
    titleAm: "JSX Стерилизация салона  AM",
    titleRu: "JSX Стерилизация салона Ru",
    titleEn: "JSX Стерилизация салона En",
    titleGe: "JSX Стерилизация салона GE",
    descAm: '[{"type":"paragaph","children":[{"text":""}]}]',
    descRu: '[{"type":"paragaph","children":[{"text":""}]}]',
    descEn: '[{"type":"paragaph","children":[{"text":""}]}]',
    descGe: '[{"type":"paragaph","children":[{"text":""}]}]',
    updatedAt: "2023-03-22T10:39:52.652Z",
    createdAt: "2023-03-22T10:39:52.652Z",
  },
];

module.exports = data;
